name: ox_usercenter
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.19.3 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter


  keframe: ^3.0.0
  pull_to_refresh_notification: ^3.1.0
  awesome_select: ^6.0.0
  flutter_cache_manager: 3.3.1

  ox_module_service:
    path: ../../base_framework/ox_module_service
  ox_common:
    path: ../../base_framework/ox_common
  ox_network:
    path: ../../base_framework/ox_network
  ox_theme:
    path: ../../base_framework/ox_theme
  ox_localizable:
    path: ../../base_framework/ox_localizable
  ox_cache_manager:
    path: ../../base_framework/ox_cache_manager
  waterfall_flow: ^3.0.2
  ox_push:
    path: ../../base_framework/ox_push

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/images/
    - assets/images/dark/
    - assets/images/light/
    - assets/locale/
#    - assets/theme/
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
